### ISSUE TITLE
Seems that this is not open

### ISSUE THREAD

**Issue by eloyesp** [infosimples/zero_captcha#1]
You may add a note about the availability of the service on the README, to warn visitors about a non available service.

On the other hand, it sounds promising :/

**Comment by barbolo** [comment]
Hi @eloyesp. The service is currently available to a small group of companies that want to solve CAPTCHAs using software. It currently supports hundreds of CAPTCHAs types and returns answers in less than 100 ms.

You can send an email to contact [at] infosimples.com so we can discuss more about your needs.
